config/routes.rb
Sociaror::Application.routes.draw do
  match '/wykops/best',  to: 'wykops#best'

  match '/pytania/best',  to: 'pytania#best'
  resources :pytania do
     member do 
      get  :like
      get  :dislike
    end
  end

  resources :wykops do
     member do 
      get  :like
      get  :dislike
    end
  end

  resources :comments, :only => [:create]
  resources :news 

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
namespace :admin do
  resources :admin, :users

  resources :news do 
    member do 
      get  :publish
      get  :unpublish
    end
  end

  resources :wykops do 
    member do 
      get  :publish
      get  :unpublish
    end
  end

  resources :pytania do 
    member do 
      get  :publish
      get  :unpublish
    end
  end
  root :to => "admin#index"
end

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'

end

app/models/wykop.rb
class Wykop < ActiveRecord::Base
  attr_accessible :status, :summary, :title, :url, :user_id
    belongs_to :user
  acts_as_commentable
    acts_as_votable

    def score
    	return self.likes.size - self.dislikes.size
    end
end

app/controllers/admin/wykops_controller.rb
class Admin::WykopsController < AdminController

  def index
    @wykops = Wykop.paginate(page: params[:page])

  end


  def show
    @wykop = Wykop.find(params[:id])

  end


  def new
    @wykop = Wykop.new

  end


  def edit
    @wykop = Wykop.find(params[:id])
  end

  def publish
    @wykop = Wykop.find(params[:id])
    @wykop.status=1
    @wykop.save
    flash[:success] = "Wykop zostal zatwierdzony"
    redirect_to admin_wykops_url 
  end  

  def unpublish
    @wykop = Wykop.find(params[:id])
    @wykop.status=0
    @wykop.save
    flash[:success] = "Wykop zostal zdjety"
    redirect_to admin_wykops_url 
  end

  def create
    @wykop = Wykop.new(params[:wykop])
    @wykop.user_id = current_user.id

      if @wykop.save
        flash[:success] = "Wykop zostal dodany"

        redirect_to admin_wykops_url 
      else
        render action: "new" 
      end
    
  end


  def update
    @wykop = Wykop.find(params[:id])

      if @wykop.update_attributes(params[:wykop])
        flash[:success] = "Wykop zostal zaktualizowany"

        redirect_to admin_wykops_url 
      else
        render action: "edit"
      end
    
  end


  def destroy
    @wykop = Wykop.find(params[:id])
    @wykop.destroy
    flash[:success] = "Wykop zostal usuniety"

    redirect_to admin_wykops_url 
  end
  
end

app/controllers/wykops_controller.rb
class WykopsController < ApplicationController
  before_filter :signed_in_user, only: [:new, :create]

  def index
    @wykops = Wykop.where(:status => 1).paginate(page: params[:page], :per_page => 5).order('id DESC')
  end

  def best
    @wykops = Wykop.where(:status => 1).paginate(page: params[:page], :per_page => 5).order('cached_votes_score ASC')
    render "index"
  end

  def show
    @wykop = Wykop.find(params[:id])
@comments = @wykop.comments.build
@wykop.comments.pop
  end


  def new
    @wykop = Wykop.new

  end


  def edit
    @wykop = Wykop.find(params[:id])
  end


  def create
    @wykop = Wykop.new(params[:wykop])
    @wykop.user_id = current_user.id

      if @wykop.save
        flash[:success] = "Wykop zostal dodany"

        redirect_to wykops_url 
      else
        render action: "new" 
      end
    
  end

  def like
    @wykop = Wykop.find(params[:id])
    
    if current_user.voted_as_when_voted_for(@wykop)==nil
      @wykop.liked_by current_user

      flash[:success] = "polubiles wpis!"

      redirect_to wykop_url(@wykop)
    else
      @wykop.unliked_by current_user

      flash[:success] = "anulowano glos"

      redirect_to wykop_url(@wykop)
    end

  end

  def dislike
    @wykop = Wykop.find(params[:id])
  
    if current_user.voted_as_when_voted_for(@wykop)==nil
      @wykop.downvote_from current_user

      flash[:success] = "wpis Ci sie nie spodobal!"

      redirect_to wykop_url(@wykop)

    else
      @wykop.unliked_by current_user

      flash[:success] = "anulowano glos"

      redirect_to wykop_url(@wykop)
    end
  end
end

app/helpers/wykops_helper.rb
module WykopsHelper
end

app/views/admin/wykops/_form.html.erb
  <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.text_area :summary, {'data-provide' => "markdown"} %>
  </div>
  <div class="field">
    <%= f.text_field :url  %>
  </div>

  <%= f.form_group :status, label: { text: "Status" } do %>
    <% if @wykop.status==0 or @wykop.status.nil? %>
      <%= f.radio_button :status, 0, label: "Nieopublikowany", inline: true , checked: true %>
    <% else %>
      <%= f.radio_button :status, 0, label: "Nieopublikowany", inline: true  %>
    <% end %>

    <% if @wykop.status==1 %>
      <%= f.radio_button :status, 1, label: "Opublikowany",inline: true  , checked: true %>
    <% else %>
      <%= f.radio_button :status, 1, label: "Opublikowany",inline: true   %>
    <% end %>
  <% end %>
  <%= f.form_group do %>
    <%= f.submit "Zapisz", class: "btn btn-large btn-primary" %>
  <% end %>

app/views/admin/wykops/_menu.html.erb
<div class="list-group">
            <a class="list-group-item active">Wykopy</a>
            <%= link_to "Listuj", admin_wykops_path, :class=>"list-group-item" %>
            <%= link_to "Dodaj", new_admin_wykop_path, :class=>"list-group-item" %>
 </div>

app/views/admin/wykops/edit.html.erb
<% provide(:title, 'Edytuj Wykop') %>
<% content_for :menu do %>
<%= render 'menu' %>
<% end %>
<h1>Edytuj Wykop</h1>
<%= bootstrap_form_for(@wykop,:url => admin_wykop_url, style: :horizontal, left: "col-sm-4", right: "col-sm-8") do |f| %>
<%= render 'form',:f => f  %>

<% end %>

app/views/admin/wykops/index.html.erb
<% provide(:title, 'Wszystkie Wykopy') %>
<% content_for :menu do %>
<%= render 'menu' %>
<% end %>
<h1>Wszystkie Wykopy</h1>

<%= will_paginate %>
              <table class="table table-striped custab">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Autor</th>
                            <th>Tytul</th>
                            <th>Status</th>
                            <th>Utworzony</th>
                            <th class="text-center">Akcje</th>
                        </tr>
                    </thead>
                      <% @wykops.each do |wykop| %>
               <tr>
                <td><%= wykop.id %></td>
                <td><%= wykop.user.name %></td>
                <td><%= wykop.title %></td>
                <td><% if wykop.status==1   %>
                    Opublikowany
                    <% else %>
                    Nieopublikowany
                    <% end %>
                </td>
                <td><%= wykop.created_at %></td>
                <td class="text-center">
                <%= link_to '<span class="glyphicon glyphicon-eye-open"></span>'.html_safe, admin_wykop_path(wykop), 
     
                :class=>"btn btn-info btn-xs"  %>
                <%= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe, edit_admin_wykop_path(wykop), 
                
                :class=>"btn btn-info btn-xs"  %>
                <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, admin_wykop_path(wykop), 
                method: :delete,
                :class=>"btn btn-danger btn-xs" ,
                data: { confirm: "You sure?" } %>
                  </td>
               </tr>
            <% end %>


        </table>


<%= will_paginate %>

app/views/admin/wykops/new.html.erb
<% provide(:title, 'Dodaj Wykop') %>
<% content_for :menu do %>
<%= render 'menu' %>
<% end %>
<h1>Dodaj Wykop</h1>
<%= bootstrap_form_for(@wykop,:url => admin_wykops_url, style: :horizontal, left: "col-sm-4", right: "col-sm-8") do |f| %>
<%= render 'form',:f => f  %>
<% end %>

app/views/admin/wykops/show.html.erb
  <% if @wykop.status==1   %>
                  <%= link_to 'Zdejmij',unpublish_admin_wykop_url(@wykop),:class =>'btn btn-danger btn-lg' %>
                    <% else %>
                    <%= link_to 'Publikuj',publish_admin_wykop_url(@wykop),:class =>'btn btn-danger btn-lg' %>
                    <% end %>
<p>
  <b>Autor:</b>
  <%= @wykop.user.name%>
</p>

<p>
  <b>Tytuł:</b>
  <%= @wykop.title %>
</p>

<p>
  <b>Podsumowanie:</b>
  <%= markdown @wykop.summary %>
</p>

<p>
  <b>Url:</b>
  <%= @wykop.url %>
</p>

<p>
  <b>Status:</b>
  <% if @wykop.status==1   %>
                    Opublikowany
                    <% else %>
                    Nieopublikowany
                    <% end %>
</p>