config/routes.rb
Sociaror::Application.routes.draw do
  match '/wykops/best',  to: 'wykops#best'

  match '/pytania/best',  to: 'pytania#best'
  resources :pytania do
     member do 
      get  :like
      get  :dislike
    end
  end

  resources :wykops do
     member do 
      get  :like
      get  :dislike
    end
  end

  resources :comments, :only => [:create]
  resources :news 

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
namespace :admin do
  resources :admin, :users

  resources :news do 
    member do 
      get  :publish
      get  :unpublish
    end
  end

  resources :wykops do 
    member do 
      get  :publish
      get  :unpublish
    end
  end

  resources :pytania do 
    member do 
      get  :publish
      get  :unpublish
    end
  end
  root :to => "admin#index"
end

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'

end

app/models/wykop.rb
class Wykop < ActiveRecord::Base
  attr_accessible :status, :summary, :title, :url, :user_id
    belongs_to :user
  acts_as_commentable
    acts_as_votable

    def score
    	return self.likes.size - self.dislikes.size
    end
end

app/controllers/admin/wykops_controller.rb
class Admin::WykopsController < AdminController

  def index
    @wykops = Wykop.paginate(page: params[:page])

  end


  def show
    @wykop = Wykop.find(params[:id])

  end


  def new
    @wykop = Wykop.new

  end


  def edit
    @wykop = Wykop.find(params[:id])
  end

  def publish
    @wykop = Wykop.find(params[:id])
    @wykop.status=1
    @wykop.save
    flash[:success] = "Wykop zostal zatwierdzony"
    redirect_to admin_wykops_url 
  end  

  def unpublish
    @wykop = Wykop.find(params[:id])
    @wykop.status=0
    @wykop.save
    flash[:success] = "Wykop zostal zdjety"
    redirect_to admin_wykops_url 
  end

  def create
    @wykop = Wykop.new(params[:wykop])
    @wykop.user_id = current_user.id

      if @wykop.save
        flash[:success] = "Wykop zostal dodany"

        redirect_to admin_wykops_url 
      else
        render action: "new" 
      end
    
  end


  def update
    @wykop = Wykop.find(params[:id])

      if @wykop.update_attributes(params[:wykop])
        flash[:success] = "Wykop zostal zaktualizowany"

        redirect_to admin_wykops_url 
      else
        render action: "edit"
      end
    
  end


  def destroy
    @wykop = Wykop.find(params[:id])
    @wykop.destroy
    flash[:success] = "Wykop zostal usuniety"

    redirect_to admin_wykops_url 
  end
  
end

app/controllers/wykops_controller.rb
class WykopsController < ApplicationController
  before_filter :signed_in_user, only: [:new, :create]

  def index
    @wykops = Wykop.where(:status => 1).paginate(page: params[:page], :per_page => 5).order('id DESC')
  end

  def best
    @wykops = Wykop.where(:status => 1).paginate(page: params[:page], :per_page => 5).order('cached_votes_score ASC')
    render "index"
  end

  def show
    @wykop = Wykop.find(params[:id])
@comments = @wykop.comments.build
@wykop.comments.pop
  end


  def new
    @wykop = Wykop.new

  end


  def edit
    @wykop = Wykop.find(params[:id])
  end


  def create
    @wykop = Wykop.new(params[:wykop])
    @wykop.user_id = current_user.id

      if @wykop.save
        flash[:success] = "Wykop zostal dodany"

        redirect_to wykops_url 
      else
        render action: "new" 
      end
    
  end

  def like
    @wykop = Wykop.find(params[:id])
    
    if current_user.voted_as_when_voted_for(@wykop)==nil
      @wykop.liked_by current_user

      flash[:success] = "polubiles wpis!"

      redirect_to wykop_url(@wykop)
    else
      @wykop.unliked_by current_user

      flash[:success] = "anulowano glos"

      redirect_to wykop_url(@wykop)
    end

  end

  def dislike
    @wykop = Wykop.find(params[:id])
  
    if current_user.voted_as_when_voted_for(@wykop)==nil
      @wykop.downvote_from current_user

      flash[:success] = "wpis Ci sie nie spodobal!"

      redirect_to wykop_url(@wykop)

    else
      @wykop.unliked_by current_user

      flash[:success] = "anulowano glos"

      redirect_to wykop_url(@wykop)
    end
  end
end

app/helpers/wykops_helper.rb
module WykopsHelper
end

app/views/wykops/_form.html.erb
<%= bootstrap_form_for(@wykop,style: :horizontal, left: "col-sm-4", right: "col-sm-8") do |f| %>

  <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.text_area :summary, {'data-provide' => "markdown"} %>
  </div>
  <div class="field">
    <%= f.text_field :url %>
  </div>
  <%= f.form_group do %>
    <%= f.submit "Zapisz", class: "btn btn-large btn-primary" %>
  <% end %>
<% end %>

app/views/wykops/_menu.html.erb
<div class="list-group">
            <a class="list-group-item active">Wykop</a>
            <%= link_to "Dodaj", new_wykop_path, :class=>"list-group-item" %>
            <% if controller.action_name=="index" %>
            <strong><%= link_to "Najnowsze", wykops_path, :class=>"list-group-item" %></strong>
            <% else %>
            <%= link_to "Najnowsze", wykops_path, :class=>"list-group-item" %>
            <% end %>

            <% if controller.action_name=="best" %>
            <strong><%= link_to "Najlepsze", wykops_best_path, :class=>"list-group-item" %></strong>
            <% else %>
            <%= link_to "Najlepsze", wykops_best_path, :class=>"list-group-item" %>
            <% end %>
            

 </div>

app/views/wykops/index.html.erb
<% provide(:title, 'Wykop') %>
<div class="row row-offcanvas row-offcanvas-right">
      <div class="col-xs-12 col-sm-9">
      

<%= will_paginate @wykops %>



<% @wykops.each do |wykop| %>
<div class="row">
	 <div class="col-md-1">

	 	<div class="wykop btn btn-primary col-md-1">
		 	<div class="row">
		 		<% if current_user.voted_for? wykop %>
		 		<span class="glyphicon glyphicon-chevron-up voted"></span>
		 		 <% else %>
		 		 <%= link_to '<span class="glyphicon glyphicon-chevron-up"></span>'.html_safe, like_wykop_path(wykop) %>
		 		 <% end %>

		 	</div>
			<div class="row">
	 			<%= wykop.score %>
	 		</div>
	 		<div class="row">
	 			<% if current_user.voted_for? wykop %>
		 		<span class="glyphicon glyphicon-chevron-down voted"></span>
		 		 <% else %>
		 		 <%= link_to '<span class="glyphicon glyphicon-chevron-down"></span>'.html_safe, dislike_wykop_path(wykop) %>
		 		 <% end %>

	 		</div>
	 		<div class="row">
	 			<% if current_user.voted_for? wykop %>
		 		  <% if current_user.voted_up_on? wykop %>
		 		 	<%= link_to 'cofnij'.html_safe, like_wykop_path(wykop) %>
		 		  <% end %>
	 			  <% if current_user.voted_down_on?wykop %>
		 		 	<%= link_to 'cofnij'.html_safe, dislike_wykop_path(wykop) %>
		 		  <% end %>
		 		<% end %>

	 		</div>

	 	</div>
	 </div>
  <div class="col-md-11">
 <div class="page-header">
          <h3><%= link_to wykop.title, wykop_url(wykop) %></h3>
        </div>
        <p>Dodane przez <%= link_to wykop.user.name, user_url(wykop.user) %>, dnia <%= time_tag wykop.created_at  ,datetime: wykop.created_at %>, napisano <%= link_to "#{wykop.comments.count} komentarzy", wykop_url(wykop) %>, url: <%= link_to wykop.url, wykop.url %></p>
        <div class="lead"><%= markdown wykop.summary %></div>
        </div>    
</div>        
<% end %>

<%= will_paginate @wykops %>

</div><!--/row-->


        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <%= render "menu" %>
        </div><!--/span-->
      </div>

app/views/wykops/new.html.erb
<% provide(:title, 'Dodaj Wykop') %>
<div class="row row-offcanvas row-offcanvas-right">
      <div class="col-xs-12 col-sm-9">
      
<h1>Dodaj Wykop</h1>

<%= render 'form' %>


</div><!--/row-->


        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <%= render "menu" %>
        </div><!--/span-->
      </div>

app/views/wykops/show.html.erb
<% provide(:title, @wykop.title ) %>
<div class="row row-offcanvas row-offcanvas-right">
      <div class="col-xs-12 col-sm-9">
 <div class="row">
   <div class="col-md-1">

    <div class="wykop btn btn-primary col-md-1">
      <div class="row">
        <% if current_user.voted_for? @wykop %>
        <span class="glyphicon glyphicon-chevron-up voted"></span>
         <% else %>
         <%= link_to '<span class="glyphicon glyphicon-chevron-up"></span>'.html_safe, like_wykop_path(@wykop) %>
         <% end %>

      </div>
      <div class="row">
        <%= @wykop.score %>
      </div>
      <div class="row">
        <% if current_user.voted_for? @wykop %>
        <span class="glyphicon glyphicon-chevron-down voted"></span>
         <% else %>
         <%= link_to '<span class="glyphicon glyphicon-chevron-down"></span>'.html_safe, dislike_wykop_path(@wykop) %>
         <% end %>

      </div>
      <div class="row">
        <% if current_user.voted_for? @wykop %>
          <% if current_user.voted_up_on? @wykop %>
          <%= link_to 'cofnij'.html_safe, like_wykop_path(@wykop) %>
          <% end %>
          <% if current_user.voted_down_on? @wykop %>
          <%= link_to 'cofnij'.html_safe, dislike_wykop_path(@wykop) %>
          <% end %>
        <% end %>

      </div>

    </div>
   </div>
  <div class="col-md-11">     
 <div class="page-header">
          <h3><%= @wykop.title %></h3>
        </div>
        <p>Dodane przez <%= link_to @wykop.user.name, user_url(@wykop.user) %>, dnia <%= time_tag @wykop.created_at  ,datetime: @wykop.created_at %>, napisano <%= link_to "#{@wykop.comments.count} komentarzy", wykop_url(@wykop) %>, url: <%= link_to @wykop.url, @wykop.url %></p>
        <div class="lead"><%= markdown @wykop.summary %></div>
    </div>
   </div>

<hr />

  <h3>Komentarze do wpisu</h3>

  <ul class="users">
  <% @wykop.comments.each do |comment| %>
    <li>


      <%= gravatar_for comment.user %><span>Napisane <%= time_ago_in_words comment.created_at %> temu, przez </span>
      <%= link_to comment.user.name, comment.user %>
      <p><%= comment.comment %></p>
    </li>
  <% end %>
</ul>
<% if signed_in? %>    
<hr />

<%= bootstrap_form_for(@comments, style: :horizontal, left: "col-sm-4", right: "col-sm-8") do |f| %>


<%=  f.text_area :comment , :rows => 3 %>
<%=  f.hidden_field :commentable_id, :as => :hidden %>
<%= f.hidden_field :commentable_type, :as => :hidden %>

          <%= f.form_group do %>
        <%= f.submit "wyslij", class: "btn btn-large btn-primary" %>
        <% end %>
    <% end %>


    </div><!--/row-->


        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <%= render "menu" %>
        </div><!--/span-->
      </div>

        <% end %>