config/routes.rb
Sociaror::Application.routes.draw do
  match '/wykops/best',  to: 'wykops#best'

  match '/pytania/best',  to: 'pytania#best'
  resources :pytania do
     member do 
      get  :like
      get  :dislike
    end
  end

  resources :wykops do
     member do 
      get  :like
      get  :dislike
    end
  end

  resources :comments, :only => [:create]
  resources :news 

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
namespace :admin do
  resources :admin, :users

  resources :news do 
    member do 
      get  :publish
      get  :unpublish
    end
  end

  resources :wykops do 
    member do 
      get  :publish
      get  :unpublish
    end
  end

  resources :pytania do 
    member do 
      get  :publish
      get  :unpublish
    end
  end
  root :to => "admin#index"
end

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :first_name, :last_name, :gender, :email_visibility
  has_secure_password
  has_many :news
  has_many :wykops
  has_many :pytanium
  acts_as_voter
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_filter :admin_user

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Uytkownik zostal usuniety."
    redirect_to admin_users_url
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end
  
  def new
  	@user = User.new
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = 'Uzytkownik zostal dodany!'
      redirect_to admin_users_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profil zostal zaktualizowany"
      redirect_to admin_users_url
    else
      render 'edit'
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  def index
    @users = User.paginate(page: params[:page], :per_page => 15)
  end

  def show
    @user = User.find(params[:id])
  end
  
  def new
  	@user = User.new
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/admin/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/_menu.html.erb
<div class="list-group">
            <a class="list-group-item active">Użytkownicy</a>
            <%= link_to "Listuj", admin_users_path, :class=>"list-group-item" %>
            <%= link_to "Dodaj", new_admin_user_path, :class=>"list-group-item" %>
 </div>

app/views/admin/users/edit.html.erb
<% provide(:title, "Edytuj użytkownika") %>
<% content_for :menu do %>
<%= render 'menu' %>
<% end %>
<h1>Edytuj użytkownika</h1>

<div class="row">
  <div class="span6 offset3">
    <%= bootstrap_form_for(@user,:url => admin_user_path, style: :horizontal, left: "col-sm-4", right: "col-sm-8") do |f| %>

        <%= f.text_field :name, placeholder: "Nazwa", help: "4-16 znaków" %>

        <%= f.text_field :email, placeholder: "login@example.com", help: "6 - max. 32 znaki, forma zgodna ze standardem adresów email"  %>

        <%= f.password_field :password, placeholder: "*****", help: "8 - 32 znaki, min. 1 cyfra, min. 1 znak specjalny, min. 1 litera"  %>

        <%= f.password_field :password_confirmation, placeholder: "*****" %>
        
        <%= f.text_field :first_name, placeholder: "Imię" %>
        
        <%= f.text_field :last_name, placeholder: "Nazwisko" %>

        <%= f.form_group :email_visibility, label: { text: "Widoczność adresu email" } do %>
          <% if @user.email_visibility==0 %>
            <%= f.radio_button :email_visibility, 0, label: "Adres Publiczny", inline: true , checked: true %>
          <% else %>
            <%= f.radio_button :email_visibility, 0, label: "Adres Publiczny", inline: true  %>
          <% end %>

          <% if @user.email_visibility==1 %>
            <%= f.radio_button :email_visibility, 1, label: "Adres Prywatny",inline: true  , checked: true %>
          <% else %>
            <%= f.radio_button :email_visibility, 1, label: "Adres Prywatny",inline: true   %>
          <% end %>
        <% end %>

        <%= f.form_group :gender, label: { text: "Pleć" } do %>
          <% if @user.gender=="m" %>
            <%= f.radio_button :gender, "m", label: "Mężczyzna", inline: true , checked: true %>
          <% else %>
            <%= f.radio_button :gender, "m", label: "Mężczyzna", inline: true  %>
          <% end %>

          <% if @user.gender=="k" %>
            <%= f.radio_button :gender, "k", label: "Kobieta",inline: true  , checked: true %>
          <% else %>
            <%= f.radio_button :gender, "k", label: "Kobieta",inline: true   %>
          <% end %>
        <% end %>

          <%= f.form_group do %>
        <%= f.submit "Zapisz", class: "btn btn-large btn-primary" %>
        <% end %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide(:title, 'Wszyscy uzytkownicy') %>
<% content_for :menu do %>
<%= render 'menu' %>
<% end %>
<h1>Użytkownicy</h1>

<%= will_paginate %>
              <table class="table table-striped custab">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nick</th>
                            <th>Email</th>
                            <th>Utworzony</th>
                            <th class="text-center">Akcje</th>
                        </tr>
                    </thead>
                      <% @users.each do |user| %>
               <tr>
                <td><%= user.id %></td>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= user.created_at %></td>
                <td class="text-center">
                <%= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe, edit_admin_user_path(user), 
                method: :delete,
                :class=>"btn btn-info btn-xs"  %>
                <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, admin_user_path(user), 
                method: :delete,
                :class=>"btn btn-danger btn-xs" ,
                data: { confirm: "You sure?" } %>
                  </td>
               </tr>
            <% end %>


                    </table>


<%= will_paginate %>

app/views/admin/users/new.html.erb
<% provide(:title, 'Dodaj uzytkownika') %>
<% content_for :menu do %>
<%= render 'menu' %>
<% end %>
<h1>Dodaj użytkownika</h1>

<div class="row">
  <div class="span6 offset3">
    <%= bootstrap_form_for(@user,:url => new_admin_user_path, style: :horizontal, left: "col-sm-4", right: "col-sm-8") do |f| %>

        <%= f.text_field :name, placeholder: "Nazwa", help: "4-16 znaków" %>

        <%= f.text_field :email, placeholder: "login@example.com", help: "6 - max. 32 znaki, forma zgodna ze standardem adresów email"  %>

        <%= f.password_field :password, placeholder: "*****", help: "8 - 32 znaki, min. 1 cyfra, min. 1 znak specjalny, min. 1 litera"  %>

        <%= f.password_field :password_confirmation, placeholder: "*****" %>
        
        <%= f.text_field :first_name, placeholder: "Imię" %>
        
        <%= f.text_field :last_name, placeholder: "Nazwisko" %>

        <%= f.form_group :email_visibility, label: { text: "Widoczność adresu email" } do %>
          <% if @user.email_visibility==0 %>
            <%= f.radio_button :email_visibility, 0, label: "Adres Publiczny", inline: true , checked: true %>
          <% else %>
            <%= f.radio_button :email_visibility, 0, label: "Adres Publiczny", inline: true  %>
          <% end %>

          <% if @user.email_visibility==1 %>
            <%= f.radio_button :email_visibility, 1, label: "Adres Prywatny",inline: true  , checked: true %>
          <% else %>
            <%= f.radio_button :email_visibility, 1, label: "Adres Prywatny",inline: true   %>
          <% end %>
        <% end %>

        <%= f.form_group :gender, label: { text: "Pleć" } do %>
          <% if @user.gender=="m" %>
            <%= f.radio_button :gender, "m", label: "Mężczyzna", inline: true , checked: true %>
          <% else %>
            <%= f.radio_button :gender, "m", label: "Mężczyzna", inline: true  %>
          <% end %>

          <% if @user.gender=="k" %>
            <%= f.radio_button :gender, "k", label: "Kobieta",inline: true  , checked: true %>
          <% else %>
            <%= f.radio_button :gender, "k", label: "Kobieta",inline: true   %>
          <% end %>
        <% end %>

          <%= f.form_group do %>
        <%= f.submit "Zarejestruj", class: "btn btn-large btn-primary" %>
        <% end %>



    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>