config/routes.rb
Sociaror::Application.routes.draw do
  match '/wykops/best',  to: 'wykops#best'

  match '/pytania/best',  to: 'pytania#best'
  resources :pytania do
     member do 
      get  :like
      get  :dislike
    end
  end

  resources :wykops do
     member do 
      get  :like
      get  :dislike
    end
  end

  resources :comments, :only => [:create]
  resources :news 

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
namespace :admin do
  resources :admin, :users

  resources :news do 
    member do 
      get  :publish
      get  :unpublish
    end
  end

  resources :wykops do 
    member do 
      get  :publish
      get  :unpublish
    end
  end

  resources :pytania do 
    member do 
      get  :publish
      get  :unpublish
    end
  end
  root :to => "admin#index"
end

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'

end

app/views/admin/admin/index.html.erb
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>Witaj Adminie!</h1>
            <p>Tutaj możesz zarządzać stroną, dodawać i usuwać użytkowników, edytować treści zamieszczone na witrynie jak i dokonywać konserwacji systemu</p>
          </div>
          <div class="row">
            <div class="col-6 col-sm-6 col-lg-6">
              <h2>Newsy</h2>
              <table class="table table-striped custab">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Tytul</th>
                            <th>Autor</th>
                            <th class="text-center">Akcje</th>
                        </tr>
                    </thead>
                    <% @news.each do |newss| %>
                         <tr>
                          <td><%= newss.id %></td>
                          <td><%= newss.title %></td>
                          <td><%= newss.user.name %></td>
                          
                          <td class="text-center"><%= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe, edit_admin_news_path(newss), 
                :class=>"btn btn-info btn-xs"  %>
                <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, admin_news_path(newss), 
                method: :delete,
                :class=>"btn btn-danger btn-xs" ,
                data: { confirm: "You sure?" } %></td>
                         </tr>
                      <% end %>
    
                    </table>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-6">
              <h2>Użytkownicy</h2>
              <table class="table table-striped custab">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nick</th>
                            <th>Email</th>
                            <th class="text-center">Akcje</th>
                        </tr>
                    </thead>
                    	<% @users.each do |user| %>
					     <tr>
					      <td><%= user.id %></td>
					      <td><%= user.name %></td>
					      <td><%= user.email %></td>
					      <td class="text-center">                <%= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe, edit_admin_user_path(user), 
                :class=>"btn btn-info btn-xs"  %>
                <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, admin_user_path(user), 
                method: :delete,
                :class=>"btn btn-danger btn-xs" ,
                data: { confirm: "You sure?" } %></td>
					     </tr>
					  <% end %>


                    </table>
            </div><!--/span-->           
           </div><!--/row-->